// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BeerNear.iOS
{
	public partial class BadgeTableCell : UITableViewCell
	{
		public BadgeTableCell() : base()
		{
		}

		public BadgeTableCell (IntPtr handle) : base (handle)
		{
		}

		public void BindDataToCell(Badge badge)
		{
			this.BadgeName.Text = badge.BadgeName;
			this.BadgeDescription.Text = badge.BadgeDescription;
			// TODO: Bind additional properties
		}
	}
}
