// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Dialog.Utilities;

namespace BeerNear.iOS
{
	public partial class BadgesTableCell : UITableViewCell
	{
		public BadgesTableCell() : base()
		{
		}

		public BadgesTableCell (IntPtr handle) : base (handle)
		{
		}

		public void BindDataToCell(Badge badge)
		{
			this.BadgeName.Text = badge.BadgeName;
			this.BadgeDescription.Text = badge.BadgeDescription;
			// TODO: Replace with valid fallback image.
//			this.BadgeImage.Image = ImageLoader.DefaultRequestImage (new Uri ("https://www.google.com/images/srpr/logo11w.png"), this) ?? null;
			// TODO: Bind additional properties
		}
	}
}
