// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Dialog.Utilities;

namespace BeerNear.iOS
{
	public partial class BadgesTableCell : UITableViewCell
	{
		public BadgesTableCell() : base()
		{
		}

		public BadgesTableCell (IntPtr handle) : base (handle)
		{
		}

		public void BindDataToCell(int cellTag, Badge badge)
		{
			this.Tag = cellTag;
			this.BadgeName.Text = badge.BadgeName;
			this.BadgeDescription.Text = badge.BadgeDescription;
			if (badge.BadgeImageMedium != null) {
				this.BadgeImage.Image = new UIImage (NSData.FromArray (badge.BadgeImageMedium));
			}

			// TODO: Consider loading fallback placeholder image if the image is not available.
		}
	}
}
